# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Ū
title: " "
fname: andrius
mname: d
lname: ilgūnas
email:
description: >- # this means to ignore newlines until "baseurl:"
  Protean IT professional offering a unique blend of
  15 years of advanced Linux Engineering and
  over 7 years experience of varsity-level Python Development, expert in
  developing and maintaining high-performance and robust software systems,
  specializing in systems automation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andrius-d-ilgunas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
domain: andrius-d-ilgunas.github.io
show_downloads: false   #or "true" (unquoted) to indicate whether to provide a download URL]
google_analytics:

# Build settings
theme: minima
# theme:  jekyll-theme-midnight
theme:  jekyll-theme-hacker
#remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
plugins:
  # - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
